### PR TITLE
Fix FormatEnumerable calling GetEnumerator, causing an exception to be thrown

### PR DESCRIPTION
**Pull request by hughbe**
Fixes xunit/xunit#987
## Discussion
- Is this case common?
- Does this commonality matter, since this addition makes the code more resilient

/cc @bradwilson

### CODE REVIEW

**Comment by bradwilson** [comment]
My question about this: why is `IEnumerable` special (as opposed to calling `ToString()`, for example)? Shouldn't a generalized strategy be applied here for all argument formatting?

Also, I think a quiet swallowing is probably wrong. We should at least give some indication that we tried to render a value, and that it failed with an exception.

**Comment by hughbe** [comment]
> Shouldn't a generalized strategy be applied here for all argument formatting?
> ... We should at least give some indication that we tried to render a value, and that it failed with an exception.

I'm not sure how obvious we want to be. It feels odd wrapping this small block of code as opposed to the entire method in an exception block.
Maybe something like "Could not format object of type "Type"" would work?

**Comment by hughbe** [comment]
On the other hand, what if only one part of formatting fails (e.g. enumeration), and ToString returns something that actually makes sense?

**Comment by bradwilson** [comment]
Hmm, that's a good point. So maybe adding an outer try/catch around the public Format method would be in addition to this rather than instead of this.

**Comment by bradwilson** [comment]
Thanks!

**Pull request merged**
