### PR TITLE
[#2683] Saravana Add inline collection comparison feature

### PR DESCRIPTION
**Pull request by SARAVANA1501**
[#2683] Add capability to pass inline comparison for collections

### CODE REVIEW

**Comment by bradwilson** [comment]
I don't believe this PR address the requested [feature](https://github.com/xunit/xunit/issues/2692).

The idea here is to replace the comparer for individual items, since that's what `IEqualityComparer` is doing here with collections: https://github.com/xunit/assert.xunit/blob/03f262badc3740e84e0d2b1a994d0d7dba0c8e51/CollectionAsserts.cs#L441-L458

The comparer is here based on `T`, which is the element type, not the collection itself. The signature we'd be looking for here is:

```csharp
public static void Equal<T>(
    IEnumerable<T> expected,
    IEnumerable<T> actual,
    Func<T, T, bool> comparerFunc)
```

In addition, you'll note in the source quoted above that null collections are acceptable inputs.

**Comment by SARAVANA1501** [comment]
@bradwilson Updated the signature, i have to cover couple of cases in unit, please verify the signature and draft implementation and will start with unit testing.

**Comment by vc-74** [comment]
@bradwilson An `Action` would be a better choice than a `Func` to be able to handle more than 1 assertion and return explicit error messages.

For instance:

```chsarp
IEnumerable<Customer> col1 ...
IEnumerable<Customer> col2 ...

Assert.Equal(col1, col2, (expected, actual) =>
{
    Assert.Equal(expected.FirstName, actual.FirstName);
    Assert.True((expected.LastName.ToLower() == actual.LastName.ToLower()),
        "Error message here");
    ...
});
```

**Comment by SARAVANA1501** [comment]
Make sense, I will update it

**Comment by bradwilson** [comment]
@vc-74 Yes, of course you're right. 😄

**Comment by bradwilson** [comment]
I believe this is a duplicate of the PR merged here: c8b052ea74218d79437670f8fa3e2f52c7b5a268

Thanks for the submission!

**Pull request closed without merging**
