### PR TITLE
Added Assert.Distinct method

### PR DESCRIPTION
**Pull request by exyi**
It asserts that all objects in the collection are distinct. It can be emulated by calling `Assert.Equal(collection.Count(), collection.Distinct().Count()`, but the error message is not helpful in that case.

I'm not sure how could I create tests for this function, when it is in a different repository. Should I also open PR there. Also sorry for not open an issue first as I already had the code at hand, we can certainly discuss here.

### CODE REVIEW

**Comment by exyi** [comment]
Hello! What do you think of this addition? Should I fix something or add test (somewhere)?

**Comment by bradwilson** [comment]
Thanks! Sorry for the delay in responding. This is definitely something we would be interested in. Opening a separate PR for the unit tests is typically how you would do that.

**Comment by exyi** [comment]
Hello! Sorry for another delay, unsurprisingly I forgot about this and found randomly 2y later :sweat_smile: 

Do you mean the xunit/xunit repository? I have just tried today, unfortunately, I was unable to get the unit tests running, it was constantly failing on some weird glitches :/

Now I'm getting this error:

```
Could not find 'msbuild.exe' on the system PATH. Please run the build from a developer command prompt.
```

Also, the build script refuses to rebuild the project unless I do `git clean -xfd`. Sometimes I got it running (I can't figure out why), but it says it's running on `64-bit .NET Core 4.6.30321.06`. I though they skipped version 4 and I certainly don't have it installed. It was failing on random NotImplementedExceptions, for example:

```
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
           at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
```


Do you have any idea what could be wrong?

I'm on Linux and don't have easy access to a Windows machine at the moment.

**Comment by bradwilson** [comment]
Hmm, I regularly use Linux for building; our PR runs all tests on Linux, Windows, and macOS, and our CI builds which make the final packages also runs on Linux. So we definitely know it runs on Linux. 😁 

As for `64-bit .NET Core 4.6.30321.06`, that's the version number that they give us programmatically. We make no attempt to translate that into the "user facing" version number (AFAIK, there isn't necessarily a easy way for us to know this).

The lack of `msbuild.exe` comes from the fact that we run tests via MSBuild, so we need access to it. If you're on Linux with Mono installed, you're good to go; if you're on Windows, you need to be running from a command prompt (CMD or PowerShell) that includes the Visual Studio tooling on the PATH. The simplest way to do this is to launch "Developer Command Prompt for VSxxxx" or "Developer PowerShell for VSxxxx" and run the commands from where. You can verify that `msbuild` is on the command line in PowerShell by running `Get-Command msbuild` and making sure you get a value.

Here is without it:

image

And here is with it:

image

**Comment by bradwilson** [comment]
Thanks!

**Comment by exyi** [comment]
Thanks for accepting the PR, looking forward to use it :)

**Pull request merged**
