### PR TITLE
#2621 Check that property getter in equivalence check logic is public and non-static

### LINKED ISSUE #2621: `Assert.Equivalent` doesn't ignore non-public properties
`Assert.Equivalent` docs say it only checks public instance properties, but it actually checks public and non-public, instance and static properties.

Repro
```cs
using Xunit;

namespace Test;

public static class Program
{
    public static void Main()
    {
        var a = new A(123);
        var b = new B(123);

        Assert.Equivalent(a, b);
    }
}

public class A
{
    private static int _ignoreMeStatic { get; set; }

    internal int _ignoreMeInstance { get; set; }

    public int Number { get; set; }

    public A(int number)
    {
        Number = number;
    }
}

public class B
{
    public int Number { get; set; }

    public B(int number)
    {
        Number = number;
    }
}
```

### PR DESCRIPTION
**Pull request by koenigst**
Fixes xunit/xunit#2621. xunit/xunit#2661 adds tests.

### CODE REVIEW

**Comment by bradwilson** [comment]
Thanks!

**Comment by koenigst** [comment]
Sorry, I'm a patter matching junkie. I have the two following suggestions which would have helped me:
* Document in the readme that c#6 is the target
* Have a build step in xunit/xunit that constrains the language version to 6

Shall I open a PR?

**Comment by bradwilson** [comment]
The issue is really a problem with the xunit/assert.xunit repo, because it has no build (a "problem" I've wanted to solve for a long time, but haven't come up with anything that I'm pleased with yet).

The core project (xunit/xunit on the `main` branch) includes several back-compat builds, which is how I end up catching these things:

https://github.com/xunit/xunit/tree/main/src/xunit.v3.assert.back-compat

I develop my assertion code directly in `src/xunit.v3.assert/Asserts`, which gives me a "dirty" submodule while developing but allows me to iterate on both the production code at the unit tests at the same time. When I'm done, I copy the modified "dirty" submodule files over into my clone of xunit/assert.xunit, commit & push, and then clean the submodule and pull a new SHA just for a final verification pass.

I do all the work in `main` since the code and tests are shared between `main` and `v2`, and my custom is to get things working in `main` and then back-port the tests (and pull in the new submodule) into `v2` as a final step after `main` is working. I don't bother with the C# 6 validation in the `v2` branch because I always do that afterwards, after I've already validated it in the `main` branch. Since you seemingly worked solely in the `v2` branch, you didn't get the benefit of the C# 6 validation builds.

So I don't think there's any PR to be done here.

**Comment by bradwilson** [comment]
I also now realize reading the README in that folder that it's out of date. 😂

**Comment by koenigst** [comment]
Correct, I worked on `v2` because I assumed fixing the released version had higher priority. Shall I put that workflow into the readme to prevent similar issues in the future? Any other updates?

**Comment by bradwilson** [comment]
Hmm, I'm not sure which README needs to be updated. Maybe several. 😂 

There is probably an opportunity for the README in this repo (xunit/assert.xunit) to describe the normal development workflow. I don't see any reason to deviate from the strategy that I use, since all code here has to support both v2 and v3, and the build system on the v3 side encapsulates the back-compat checks.

If you want to try to describe what I wrote above in the README, that'd be great! I also understand if I didn't give you enough to go on 😁 at which point the better strategy would be to open an issue for me to track the need to update the README here to describe the process.

**Pull request merged**
